tienda/apps/home/urls.py
from django.urls import path
from apps.home.views import (home)

app_name='home'

urlpatterns = [
    path('', home, name='home')

]

tienda/apps/producto/urls.py
from django.urls import path
from apps.producto.views import (index)
from apps.producto.views import (fecha)
from apps.producto.views import (edad)
from apps.producto.views import (nombre, eliminar_producto)
from apps.producto.views import (datos, home, agregar_producto, listar_productos, editar_producto, claseIndex)

app_name='producto'

urlpatterns = [
    path('index/', index, name='index'),
    path('fecha/', fecha, name='fecha'),
    path('edad/<int:nacimiento>',edad,name='edad'),
    path('nombre/<str:nombre>',nombre, name='nombre'),
    path('datos/<str:nombre>/<int:nacimiento>' ,datos,name='datos'),
    path('home/',home, name='home'),
    path('home/<str:nombre>/<str:edad>', home, name='home'),
    path('agregarProducto/', agregar_producto, name='agregarProd'),
    path('lista/', listar_productos, name='listProd'),
    path('editar/<int:id>/', editar_producto, name ='editProd'),
    path('eliminar/<int:id>/', eliminar_producto, name='elimProd'),
    path('claseIndex/', claseIndex.as_view(), name='claseIndex')
]

tienda/apps/usuario/urls.py
from django.urls import path
from apps.usuario.views import *

app_name='usuario'

urlpatterns = [
    path('claseIndex/', claseIndex.as_view(), name='index'),
    path('registro/', RegistroView.as_view(), name='registro'),
    path('vendedor/home/', vendedor_home, name='vendedor_home'),
    path('cliente/home/', cliente_home, name='cliente_home'), 
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('cliente/perfil/', UserDetailViewCliente.as_view(), name='perfil_cliente'),
    path('vendedor/perfil/', UserDetailViewVendedor.as_view(), name='perfil_vendedor'),
    path('editar/', UserEditView.as_view(), name='editar_usuario'),
    path('eliminar/', UserDeleteView.as_view(), name='eliminar_usuario'),

]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
from apps.home.views import home

#from apps.producto import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('producto/', include('apps.producto.urls')),
    path('carrito/', include('apps.carrito.urls')),
    path('venta/', include('apps.venta.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('home/', include('apps.home.urls')),

    path('', home, name='home')
    
]

urlpatterns += static( 'media/', document_root = settings.MEDIA_ROOT) 

tienda/apps/home/models.py
from django.db import models

# Create your models here.

tienda/apps/home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html')

tienda/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Tienda</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
    

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace+SC&display=swap" rel="stylesheet">


    <script src="https://kit.fontawesome.com/023df603b2.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <header>
        <nav> 
            <ul>
                <li><a href="{% url "usuario:index" %}">Entrar</a></li>
                <li><a href="{% url 'producto:listProd' %}">Lista de Productos</a></li>
           
            </ul>
        </nav>
    </header>

</body>
</html>