tienda/apps/carrito/urls.py
from django.urls import path
from apps.carrito.views import *

app_name='carrito'

urlpatterns = [
    path('agregar/<int:id>/', agregar_carrito, name='agregar_carrito'),
    path('', ver_carrito, name='ver_carrito'),
    path('eliminar/<int:id>/', eliminar_producto_carrito, name='eliminar_producto_carrito'),
    path('incrementar/<int:id>/', incrementar_cantidad_producto_carrito, name='incrementar_cantidad_producto_carrito'),
    path('decrementar/<int:id>/', decrementar_cantidad_producto_carrito, name='decrementar_cantidad_producto_carrito'),
]

tienda/apps/usuario/urls.py
from django.urls import path
from apps.usuario.views import *

app_name='usuario'

urlpatterns = [
    path('claseIndex/', claseIndex.as_view(), name='index'),
    path('registro/', RegistroView.as_view(), name='registro'),
    path('vendedor/home/', vendedor_home, name='vendedor_home'),
    path('cliente/home/', cliente_home, name='cliente_home'), 
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('cliente/perfil/', UserDetailViewCliente.as_view(), name='perfil_cliente'),
    path('vendedor/perfil/', UserDetailViewVendedor.as_view(), name='perfil_vendedor'),
    path('editar/', UserEditView.as_view(), name='editar_usuario'),
    path('eliminar/', UserDeleteView.as_view(), name='eliminar_usuario'),

]

tienda/apps/venta/urls.py
from django.urls import path
from apps.venta.views import *

app_name='venta'

urlpatterns = [
    path('compra/exitosa/', compra_exitosa, name='compra_exitosa'),
    path('realizar_compra/', realizar_compra, name='realizar_compra'),
    path('ventas/vendedor/', ventas_vendedor, name='ventas_vendedor'),
    path('compras/cliente/', compras_cliente, name='compras_cliente'),
    path('ventasPDF/<int:pk>', ListVentasPdf.as_view(),name='ventasPDF'), 
    path('vanetasJSON/<int:pk>',ListVentasJson.as_view(),name='ventasJSON'),
    
]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
from apps.home.views import home

#from apps.producto import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('producto/', include('apps.producto.urls')),
    path('carrito/', include('apps.carrito.urls')),
    path('venta/', include('apps.venta.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('home/', include('apps.home.urls')),

    path('', home, name='home')
    
]

urlpatterns += static( 'media/', document_root = settings.MEDIA_ROOT) 

tienda/apps/usuario/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class TipoUsuario(models.Model):
    CLIENTE = 'Cliente'
    VENDEDOR = 'Vendedor'
    TIPO_USUARIO_OPCIONES =[
        (CLIENTE, 'Cliente'),
        (VENDEDOR, 'Vendedor'),
    ]

    usuario= models.OneToOneField(User, on_delete=models.CASCADE)
    tipo_usuario = models.CharField(max_length=10, choices = TIPO_USUARIO_OPCIONES, default=CLIENTE)

    def __str__(self):
        return f"{self.usuario.username} ({self.usuario.first_name} {self.usuario.last_name})"

tienda/apps/usuario/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import TipoUsuario

class RegistroForm(UserCreationForm):
    email = forms.EmailField(required=True)
    tipo_usuario = forms.ChoiceField(choices=TipoUsuario.TIPO_USUARIO_OPCIONES, required=True)

    class Meta:
        model = User
        fields = ("username", 'first_name', 'last_name', "email", "password1", "password2", "tipo_usuario")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
            tipo_usuario = TipoUsuario(usuario=user, tipo_usuario=self.cleaned_data["tipo_usuario"])
            tipo_usuario.save()
        return user
    
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", 'first_name', 'last_name', 'email']  # Añade los campos que necesites

class TipoUsuarioEditForm(forms.ModelForm):
    class Meta:
        model = TipoUsuario
        fields = ['tipo_usuario']

tienda/apps/usuario/views.py
from .forms import RegistroForm
from django.views.generic import View,TemplateView, DetailView, UpdateView, DeleteView
from django.shortcuts import redirect, render 
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from .forms import RegistroForm, UserEditForm, TipoUsuarioEditForm
from django.urls import reverse_lazy, reverse

from .models import TipoUsuario
class RegistroView(View):
   form_class = RegistroForm
   template_name = 'usuario/registro.html'

   def get(self, request, *args, **kwargs):
       form = self.form_class()
       return render(request, self.template_name, {'form': form})

   def post(self, request, *args, **kwargs):
       form = self.form_class(request.POST)
       if form.is_valid():
           form.save()
           return redirect('producto:home')  # Suponiendo que tienes una URL de login
       return render(request, self.template_name, {'form': form})
   
class claseIndex(TemplateView):
   template_name = "usuario/index.html"

def vendedor_home(request):
   return render(request, 'usuario/vendedor_home.html')

def cliente_home(request):
   return render(request, 'usuario/cliente_home.html')

def user_login(request):
   if request.method == 'POST':
       form = AuthenticationForm(request, data=request.POST)
       if form.is_valid():
           username = form.cleaned_data.get('username')
           password = form.cleaned_data.get('password')
           user = authenticate(username=username, password=password)
           if user is not None:
               login(request, user)
               tipo_usuario = TipoUsuario.objects.get(usuario=user)
               if tipo_usuario.tipo_usuario == TipoUsuario.VENDEDOR:
                   return redirect('usuario:vendedor_home')  # URL para el homepage del vendedor
               else:
                   return redirect('usuario:cliente_home')  # URL para el homepage del client
   else:
       form = AuthenticationForm()
   return render(request, 'usuario/login.html', {'form': form})

def user_logout(request):
   logout(request)
   return redirect('usuario:index')

class UserDetailViewCliente(LoginRequiredMixin, DetailView):
   model = User
   template_name = 'usuario/perfil_cliente.html'

   def get_object(self):
       return self.request.user

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       usuario = self.get_object()
       context['usuario'] = usuario
       context['tipo_usuario'] = TipoUsuario.objects.filter(usuario=usuario).first()
       return context
   
class UserDetailViewVendedor(LoginRequiredMixin, DetailView):
   model = User
   template_name = 'usuario/perfil_vendedor.html'

   def get_object(self):
       return self.request.user

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       usuario = self.get_object()
       context['usuario'] = usuario
       context['tipo_usuario'] = TipoUsuario.objects.filter(usuario=usuario).first()
       return context
   
class UserEditView(LoginRequiredMixin, UpdateView):
   model = User
   form_class = UserEditForm
   template_name = 'usuario/actualizar.html'
   success_url=reverse_lazy('usuario:perfil_cliente')

   def get_object(self):
       return self.request.user

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       if 'tipo_usuario_form' not in context:
           context['tipo_usuario_form'] = TipoUsuarioEditForm(instance=self.get_tipo_usuario())
       return context
   
   def get_tipo_usuario(self):
       return TipoUsuario.objects.get_or_create(usuario=self.request.user)[0]

   def post(self, request, *args, **kwargs):
       self.object = self.get_object()
       form = self.get_form()
       tipo_usuario_form = TipoUsuarioEditForm(request.POST, instance=self.get_tipo_usuario())

       if form.is_valid() and tipo_usuario_form.is_valid():
           return self.form_valid(form, tipo_usuario_form)
       else:
           return self.form_invalid(form, tipo_usuario_form)

   def form_valid(self, form, tipo_usuario_form):
       self.object = form.save()
       tipo_usuario_form.save()
       return super().form_valid(form)

   def form_invalid(self, form, tipo_usuario_form):
       return self.render_to_response(self.get_context_data(form=form, tipo_usuario_form=tipo_usuario_form))
   
class UserDeleteView(LoginRequiredMixin, DeleteView):
   model = User
   template_name = 'usuario/eliminar.html'

   def get_object(self):
       return self.request.user

   def get_success_url(self):
       return reverse('usuario:index')

   def delete(self, request, *args, **kwargs):
       usuario = self.get_object()
       tipo_usuario = TipoUsuario.objects.filter(usuario=usuario).first()
       tipo_usuario.delete()
       usuario.delete()
       return super().delete(request, *args, **kwargs)

tienda/templates/usuario/actualizar.html
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Editar Usuario</title>
</head>
<body>
    <h1>Editar Usuario</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ tipo_usuario_form.as_p }}
        <button type="submit">Guardar Cambios</button>
    </form>
    <a href="{% url 'usuario:perfil_cliente' %}">Regresar</a>
</body>
</html> 

tienda/templates/usuario/cliente_home.html
<p>Cliente</p>
<a href="{% url 'usuario:logout' %}">Cerrar Sesión</a>
<a href="{% url 'usuario:perfil_cliente' %}">Perfil</a>
<a href="{% url 'carrito:ver_carrito' %}">Carrito</a>
<a href="{% url 'venta:compras_cliente' %}">Compras</a>

<ul>
    {% for producto in productos %}
        <li>
            {%if producto.stock > 0%}
                {{ producto.nombre }}
                <a href="{% url 'agregar_carrito' producto.id %}">Agregar al Carrito</a>
            {%else%}
                {{ producto.nombre }} 
                Producto Agotado
            {%endif%}
            Precio: {{ producto.precio }}
            Descripción:{{ producto.descripcion }}
            {%if producto.imagen.url%}
                <td>
                    <img src="{{producto.imagen.url}}" width="100" height="100"></img>
                </td>
            {%else%}
                <td> Imagen no disponible </td>
            {%endif%}
        </li>
    {% endfor %}
 </ul>
 

tienda/templates/usuario/eliminar.html
<form action="{% url 'usuario:eliminar_usuario'%}" method="POST">
    {% csrf_token %}
    ¿Desea eliminar su cuenta?
    <button type="submit">Eliminar</button>
 </form>
 <a href="{% url 'usuario:index' %}">Regresar</a>

tienda/templates/usuario/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">


    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace+SC&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/023df603b2.js" crossorigin="anonymous"></script>
    

</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'usuario:registro' %}">Registro</a></li>
                <li><a href="{% url 'usuario:login' %}">Login</a></li>
                <!-- Puedes agregar más enlaces aquí si es necesario -->
            </ul>
        </nav>
    </header>
    <main>
        
    </main>
</body>
</html>

tienda/templates/usuario/login.html
<html>
<head>
    <title>Iniciar Sesión</title>
</head>
<body>
    {% include "header.html"%}
    <h2>Iniciar Sesión</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Iniciar Sesión</button>
    </form>
    {% include "footer.html"%}
</body>
</html>

tienda/templates/usuario/perfil_cliente.html
perfil_cliente:
<h1>Detalles de Perfil</h1>

<p><b>Nombre de usuario:</b> {{ usuario.username }}</p>
<p><b>Nombre:</b> {{ usuario.first_name }} {{ usuario.last_name }}</p>
<p><b>Correo electrónico:</b> {{ usuario.email }}</p>
<p><b>Tipo de usuario:</b> {{ tipo_usuario }}</p>

<a href="{% url 'usuario:perfil_cliente' %}">Regresar</a>
<a href="{% url 'usuario:editar_usuario' %}">Editar</a>
<a href="{% url 'usuario:eliminar_usuario' %}">Eliminar</a> 

<form action="{% url 'usuario:eliminar_usuario'%}" method="POST">
    {% csrf_token %}
    ¿Desea eliminar su cuenta?
    <button type="submit">Eliminar</button>
    </form>
    <a href="{% url 'usuario:perfil_cliente' %}">Regresar</a>

tienda/templates/usuario/registro.html
<html>
<head>
    <title>Registro</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace+SC&display=swap" rel="stylesheet">


    <script src="https://kit.fontawesome.com/023df603b2.js" crossorigin="anonymous"></script>
    
</head>
<body>
    {% include "header.html"%}

    <main>
        <h2>Registro de Usuario</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Registrar</button>
        </form>
        <a href="{% url 'usuario:index' %}">Regresar</a>
        {% include "footer.html"%}
    </main>
</body>
</html> 

tienda/templates/usuario/vendedor_home.html
<p>Vendedor</p>
<a href="{% url 'usuario:logout' %}">Cerrar Sesión</a>
<a href="{% url 'usuario:perfil_vendedor' %}">Perfil</a>
<a href="{% url 'venta:ventas_vendedor' %}">Ventas</a>