tienda/apps/usuario/urls.py
from django.urls import path
from apps.usuario.views import *

app_name='usuario'

urlpatterns = [
    path('claseIndex/', claseIndex.as_view(), name='index'),
    path('registro/', RegistroView.as_view(), name='registro'),
    path('vendedor/home/', vendedor_home, name='vendedor_home'),
    path('cliente/home/', cliente_home, name='cliente_home'), 
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('cliente/perfil/', UserDetailViewCliente.as_view(), name='perfil_cliente'),
    path('vendedor/perfil/', UserDetailViewVendedor.as_view(), name='perfil_vendedor'),
    path('editar/', UserEditView.as_view(), name='editar_usuario'),
    path('eliminar/', UserDeleteView.as_view(), name='eliminar_usuario'),

]

tienda/apps/venta/urls.py
from django.urls import path
from apps.venta.views import *

app_name='venta'

urlpatterns = [
    path('compra/exitosa/', compra_exitosa, name='compra_exitosa'),
    path('realizar_compra/', realizar_compra, name='realizar_compra'),
    path('ventas/vendedor/', ventas_vendedor, name='ventas_vendedor'),
    path('compras/cliente/', compras_cliente, name='compras_cliente'),
    path('ventasPDF/<int:pk>', ListVentasPdf.as_view(),name='ventasPDF'), 
    path('vanetasJSON/<int:pk>',ListVentasJson.as_view(),name='ventasJSON'),
    
]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
from apps.home.views import home

#from apps.producto import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('producto/', include('apps.producto.urls')),
    path('carrito/', include('apps.carrito.urls')),
    path('venta/', include('apps.venta.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('home/', include('apps.home.urls')),

    path('', home, name='home')
    
]

urlpatterns += static( 'media/', document_root = settings.MEDIA_ROOT) 

tienda/apps/venta/models.py
from django.db import models
from apps.producto.models import Producto
from django.contrib.auth.models import User

# Create your models here.
class ItemVenta(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio = models.DecimalField(max_digits = 6, decimal_places=2)

    def __str__(self):
       return f"{self.producto.nombre} x{self.cantidad}"
    
    class Meta:
       verbose_name = "item_venta"
       verbose_name_plural = "items_ventas"
       ordering=['precio']
       unique_together=('producto','precio') 

class Venta(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(ItemVenta)
    fecha_venta = models.DateTimeField(auto_now_add = True)  

 

tienda/apps/venta/views.py
from django.views.generic import DetailView
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.shortcuts import redirect, render 
from apps.venta.models import *
import io
from django.http import JsonResponse
from django.core.serializers import serialize
import json
from django.utils import timezone
from apps.carrito.models import ItemCarrito

class ListVentasPdf(DetailView):
    model=Venta
    def get(self,request,*args,**kwargs):
        venta=self.get_object()
        data={
            'venta':venta
        }
        fecha_venta_str = venta.fecha_venta.strftime("%Y%m%d")  # o el formato de fecha que prefieras
        name_pdf = str(venta.usuario).replace(' ', '') + "_" + str(venta.id).replace(' ', '') + "_" + fecha_venta_str + ".pdf"
        #Obtener datos y renderizar el template
        template=get_template('venta/ventaDetail.html')
        html=template.render(data)
        # Crear el archivo PDF en memoria
        result=io.BytesIO()
        pdf=pisa.CreatePDF(io.StringIO(html),result)
        # Crear la respuesta HTTP
        if not pdf.err:
            pdf=HttpResponse(result.getvalue(),content_type="application/pdf")
            pdf['Content-Disposition'] = 'inline; filename="%s"' % name_pdf
        else:
            pdf=HttpResponse(status=500) 
        return pdf

class ListVentasJson(DetailView):
    model = Venta
    def get(self, request, *args, **kwargs):
        venta = self.get_object()
        # Formato de nombre de archivo similar al PDF
        fecha_venta_str = venta.fecha_venta.strftime("%Y%m%d")
        name_json = "{}_{}_{}.json".format(venta.usuario.username.replace(' ', ''), venta.id, fecha_venta_str)
        # Serializar los datos de la venta
        venta_data = json.loads(serialize('json', [venta]))
        items_data = json.loads(serialize('json', venta.items.all()))
        # Crear un diccionario con los datos serializados
        response_data = {
            'venta': venta_data,
            'items': items_data
        }
        # Convertir el diccionario a JSON
        json_data = json.dumps(response_data, indent=4)
        # Crear la respuesta HTTP
        response = HttpResponse(json_data, content_type='application/json')
        response['Content-Disposition'] = 'attachment; filename="{}"'.format(name_json)
        return response


def compra_exitosa(request):
   return render(request, 'venta/compra_exitosa.html')

def realizar_compra(request):
   items_carrito = ItemCarrito.objects.filter(usuario=request.user)
   venta = Venta.objects.create(usuario=request.user, fecha_venta=timezone.now())
   for item in items_carrito:
       item_venta = ItemVenta.objects.create(
           producto=item.producto,
           cantidad=item.cantidad,
           precio=item.producto.precio)
       venta.items.add(item_venta)
       item.producto.save()
       item.delete()
   return redirect('venta:compra_exitosa')

def ventas_vendedor(request):
   ventas = Venta.objects.filter(items__producto__vendedor=request.user).distinct().prefetch_related('items')
   return render(request, 'venta/ventas_vendedor.html', {'ventas': ventas})

def compras_cliente(request):
   ventas = Venta.objects.filter(usuario=request.user).prefetch_related('items')
   return render(request, 'venta/compras_cliente.html', {'ventas': ventas})

tienda/templates/venta/compra_exitosa.html
<body>
    <h1>¡Compra Realizada con Éxito!</h1>
    <p>Tu compra ha sido procesada exitosamente.</p>
    <a href="{% url 'usuario:cliente_home' %}">Volver a la Tienda</a>
</body>

tienda/templates/venta/compras_clientes.html
<body>
    <h1>Mis Compras</h1>
    {% for venta in ventas %}
        <h2>Venta ID: {{ venta.id }} - Fecha: {{ venta.fecha_venta }}</h2>
        <ul>
            {% for item in venta.items.all %}
                <li>{{ item.producto.nombre }} - Cantidad: {{ item.cantidad }} - Precio: {{ item.precio }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
    <a href="{% url 'usuario:cliente_home'%}">Regresar</a>
</body>

tienda/templates/venta/ventaDetail.html
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .header {
            text-align: center;
            margin-botton: 20px;
        }
        ul {
            list-style-type:  none;
            padding: 0;
        }
        li {
            margin-botton: 10px;
            border-botton: 1px solid #ddd;
            padding-botton: 10px;
        
        }
        .item {
            font-size: 16px;
        }
        .item-label {
            font-weight: bold;
        }
        .item-value {
            margin-left:10px
        }
    </style>
</head>

<body>
    <div class="header">
        <h2>Reporte de Venta</h2>
        <div>Usuario: {{ venta.usuario }}</div>
        <div>Fecha de Venta: {{ venta.fecha_venta|date:"d/m/Y H:i" }}</div>
    </div>
    
    {% for item in venta.items.all %}
    <div class="item-container">
        <div class="item">
            <span class="item-label">Producto:</span>
            <span>{{ item.producto.nombre }}</span>
        </div>
        <div class="item">
            <span class="item-label">Precio:</span>
            <span>${{ item.producto.precio }}</span>
        </div>
        <div class="item item-image">
            {% if item.producto.imagen %}
            <img src="{{ item.producto.imagen.url }}" alt="{{ item.producto.nombre }}">
            {% endif %}
        </div>
        <div class="item">
            <span class="item-label">Descripción:</span>
            <span>{{ item.producto.descripcion }}</span>
        </div>
        <div class="item">
            <span class="item-label">Cantidad:</span>
            <span>{{ item.cantidad }}</span>
        </div>
        <div class="item">
            <span class="item-label">Total:</span>
            <span>${{ item.precio }}</span>
        </div>
    </div>
    {% endfor %} 
    
 </body>
 </html> 

tienda/templates/venta/ventas_vendedor.html
<body>
    <h1>Mis Ventas</h1>
    {% for venta in ventas %}
        <h2>Venta ID: {{ venta.id }} - Fecha: {{ venta.fecha_venta }}</h2>
        <ul>
            {% for item in venta.items.all %}
                <li>{{ item.producto.nombre }} - Cantidad: {{ item.cantidad }} - Precio: {{ item.precio }}</li>
            {% endfor %}
        </ul>
        <div><a href="{% url 'venta:ventasPDF'  venta.id %}">Imprimir</a></div> 
        <div><a href="{% url 'venta:ventasJSON'  venta.id %}">Formato JSON</a></div> 
    {% endfor %}
    <a href="{% url 'usuario:vendedor_home'%}">Regresar</a>
</body>