tienda/apps/home/urls.py
from django.urls import path
from apps.home.views import (home)

app_name='home'

urlpatterns = [
    path('', home, name='home')

]

tienda/apps/producto/urls.py
from django.urls import path
from apps.producto.views import (index)
from apps.producto.views import (fecha)
from apps.producto.views import (edad)
from apps.producto.views import (nombre, eliminar_producto)
from apps.producto.views import (datos, home, agregar_producto, listar_productos, editar_producto, claseIndex)

app_name='producto'

urlpatterns = [
    path('index/', index, name='index'),
    path('fecha/', fecha, name='fecha'),
    path('edad/<int:nacimiento>',edad,name='edad'),
    path('nombre/<str:nombre>',nombre, name='nombre'),
    path('datos/<str:nombre>/<int:nacimiento>' ,datos,name='datos'),
    path('home/',home, name='home'),
    path('home/<str:nombre>/<str:edad>', home, name='home'),
    path('agregarProducto/', agregar_producto, name='agregarProd'),
    path('lista/', listar_productos, name='listProd'),
    path('editar/<int:id>/', editar_producto, name ='editProd'),
    path('eliminar/<int:id>/', eliminar_producto, name='elimProd'),
    path('claseIndex/', claseIndex.as_view(), name='claseIndex')
]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
from apps.home.views import home

#from apps.producto import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('producto/', include('apps.producto.urls')),
    path('carrito/', include('apps.carrito.urls')),
    path('venta/', include('apps.venta.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('home/', include('apps.home.urls')),

    path('', home, name='home')
    
]

urlpatterns += static( 'media/', document_root = settings.MEDIA_ROOT) 

tienda/apps/home/models.py
from django.db import models

# Create your models here.

tienda/apps/producto/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Producto (models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.DecimalField(max_digits=7, decimal_places=2)
    descripcion = models.TextField(null=True)
    imagen = models.ImageField(upload_to='imagenes_productos/', blank=True, null=True)
    vendedor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='productos')
    stock = models.IntegerField(default=0)

tienda/apps/producto/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        #fields = ['nombre', 'precio', 'descripcion', 'imagen', 'stock'] #para agregar uno a uno los que necesitemos
        #fields = '__all__' "para agarrar todos"
        #exclude = ['vendedor'] #con ese se excluye solo a vendedor y se muestran todos los demas
        fields = '__all__'

tienda/apps/home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html')

tienda/apps/producto/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
from django.template import loader
from django.shortcuts import redirect
from .forms import ProductoForm
from .models import Producto
from django.views.generic import View,TemplateView

def index(request):
    return HttpResponse("Hola amigos de YouTube")

def fecha(request):
    fecha_actual = datetime.now()
    return HttpResponse (fecha_actual)

def edad(request,nacimiento):
    anio= datetime.now().year
    edad=anio-nacimiento
    return HttpResponse(edad)

def nombre(request,nombre):
    saludo='Bienvenido ' +nombre
    return HttpResponse(saludo)

def datos (request, nombre, nacimiento):
        anio= datetime.now().year
        edad= str(anio-nacimiento)
        #saludo='Hola, ¿Cómo estás? '+nombre+ ' tienes ' +str(edad)+ ' años'
        return redirect("producto:home", nombre, edad) 

#def home(request):
#     template = loader.get_template('producto/home.html')
#     context = {}
#     return HttpResponse(template.render(context, request))

def home(request):
    cliente = {"nombre": "Ana", "apellido": "lopez"}
    productos = ["Paleta", "Chicle", "Gomitas", "Mazapán"]
    fecha = datetime.now()
    tpl = 'producto/home.html'
    contexto =  {'cliente': cliente, 'fecha': fecha, 'productos': productos}
    return render(request, tpl, contexto)

def agregar_producto(request):
    if request.method == 'POST':
        #print(request.user)
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            producto = form.save(commit=False)
            #producto.vendedor = request.user
            producto.save()
            return redirect('producto:listProd')  # Redirige a la vista de listar productos
    else:
        form = ProductoForm()
    return render(request, 'producto/agregar_producto.html', {'form': form}) 
    
def listar_productos(request):
        productos = Producto.objects.all()  # Solo muestra los productos del vendedor actual
        return render(request, 'producto/listar_producto.html', {'productos': productos}) 
    
def editar_producto(request, id):
    producto = Producto.objects.get(id=id)
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES, instance=producto)
        if form.is_valid():    
            form.save()
            return redirect('producto:listProd')
    else:
        form = ProductoForm(instance=producto)
    return render(request, 'producto/editar_producto.html', {'form': form}) 

def eliminar_producto(request, id):
    producto = Producto.objects.get(id=id)
    if request.method == 'POST':
        producto.delete()
        return redirect('producto:ListProd')
    return render(request, 'producto/eliminar_producto.html', {'producto': producto}) 

class claseIndex(TemplateView):
    template_name = "producto/index.html"

tienda/templates/producto/agregar_producto.html
<!DOCTYPE html>
<html>
    {% include "header.html" %}
<head>
    <title>Agregar Producto</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Agregar Producto</button>
    </form>
</body>
</html> 

tienda/templates/producto/editar_producto.html
<!DOCTYPE html>
<html>
    {% include "header.html" %} 
<head>
    <title>Editar Producto</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Actualizar Producto</button>
    </form>
</body>
</html> 

tienda/templates/producto/eliminar_producto.html
<!DOCTYPE html>
<html>
<head>
    <title>Eliminar Producto</title>
</head>
<body>
    <h1>¿Estás seguro de que quieres eliminar {{ producto.nombre }}?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Eliminar</button>
    </form>
    <a href="{% url 'producto:listProd' %}">Cancelar</a>
</body>
</html> 

tienda/templates/producto/home.html
<!DOCTYPE html>
<html>
    <body>
        {% include "header.html" %}      
        <h1>Bienvenido a productos! {{ cliente.nombre }}</h1>
        <p>La fecha es: {{ fecha|date:"d-M-Y H:i"}}</p> {#los atributos de date pueden cambiar si los pongo con minuscula o mayuscula(con mayuscula hay mas información)#}
        {% now "Y-m-d H:i" %}
        <p>La hora es: {{ fecha.hour }}</p>

        {%if cliente.nombre == "Ana" %}
                <p>Felicidades {{ cliente.apellido|upper}}</p>
                <p> Tienes 10% de descuento en la compra de 3 productos!!</p>
        {%endif%}

        <p>Estos son los productos disponibles: </p>
        {%  lorem 3 p random %}
        {%if productos%}
        <ul>
        {%for producto in productos%}
            <li>{{ producto }}</li>
        {%endfor%}
        </ul>
        {%else%}
            <p> No hay productos disponibles </p>
        {%endif%}
        
        {% include "footer.html" %}
        {#Comentario de una linea#}

        {%comment%} COMENTARIO DE

        VARIAS LINEAS

        {%endcomment%}
    </body>
</html>

tienda/templates/producto/index.html
nada

tienda/templates/producto/listar_producto.html
<!DOCTYPE html>
<html>
<head>
    <title>Listado de Productos</title>
</head>
<body>
    {% include "header.html" %} 
    <h1>Mis Productos</h1>
    <a href="{% url 'producto:agregarProd' %}">Agregar Producto</a> 
    <ul>
        {% for producto in productos %}
        <li>
            {{ producto.nombre }} 
            {{ producto.precio }}
            {{ producto.descripcion }}
            {{ producto.stock }}
            {%if producto.imagen %}
                <td>
                    <img src="{{producto.imagen.url}}" width="100" height="100"></img>
                </td> 
            {%else%}
                <td> Imagen no disponible </td>
            {%endif%}
                <a href="{% url 'producto:editProd' producto.id %}">Editar</a> - 
                <a href="{% url 'producto:elimProd' producto.id %}">Eliminar</a>
        </li>
        {% endfor %}
    </ul>
    <a href="{% url 'producto:home'%}">Regresar</a>
</body>
</html>